### ISSUE TITLE
Firebase extension not updating

### ISSUE THREAD

**Issue by bdytx5** [invertase/stripe-firebase-extensions#526]
# Bug report

firestore-stripe-payments extension 

## Describe the bug
the extension does not update when the update button is clicked in firebase... 

## To Reproduce

try to update the extension from the previous version to current

## Expected behavior

it should update 

## System information

chrome

**Comment by jackstruck** [comment]
Having the same problem, but it's not limited to this firebase extension alone: all of my extensions don't update. After clicking the 'Update Extension" button it just loads forever. There are no errors in the console. 
Similar reports:
https://github.com/firebase/extensions/issues/1546
https://github.com/firebase/extensions/issues/1547#issuecomment-1537053177
https://github.com/firebase/extensions/issues/1551

**Comment by TheRedSpy15** [comment]
As @jackstruck said, all of my extensions are having the same issue

**Comment by guskuma** [comment]
Same here.

**Comment by stefandouw** [comment]
Still happening unfortunately

**Comment by NashIlli** [comment]
Same!

**Comment by jackstruck** [comment]
Firebase support confirmed the issue and said they resolved it as of Friday. I can confirm I'm able to update this and other extensions. Would recommend closing this issue.

**Comment by dackers86** [comment]
Closing as issue was resolved by the Firebase team in May.

**Comment by TheRedSpy15** [comment]
Issue still persists. Keep getting a 400 error a PATCH request in the browser console and a red error message at the top of the page when clicking update button
